# Generated by Django 4.2.27 on 2025-12-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NessusScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('scan_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NessusVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=50)),
                ('plugin_name', models.CharField(max_length=500)),
                ('severity', models.IntegerField(choices=[(0, 'Info'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=0)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(blank=True, max_length=50)),
                ('protocol', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('risk_factor', models.CharField(blank=True, max_length=50)),
                ('plugin_output', models.TextField(blank=True)),
                ('cvss_score', models.CharField(blank=True, max_length=10)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='NessusParser.nessusscan')),
            ],
            options={
                'ordering': ['-severity', 'host', 'plugin_name'],
            },
        ),
    ]
